### ISSUE TITLE
HTTP Error : Error 404

### ISSUE THREAD

**Issue by dhanyathailappan** [PrimozGodec/ImageColorization#6]
While I am running the code, I got an error.

data/weights/imp9-full.h5
Downloading trained model
Traceback (most recent call last):
  File "C:\Users\Dhanya\Anaconda3\envs\tensorflow\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Dhanya\Anaconda3\envs\tensorflow\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Dhanya\Downloads\ImageColorization-master\ImageColorization-master\src\image_colorization\main.py", line 21, in <module>
    model.load_weights(get_weights(imported_model.weights))
  File "C:\Users\Dhanya\Downloads\ImageColorization-master\ImageColorization-master\src\utils\image_utils.py", line 92, in get_weights
    reporthook=show_progress)
  File "C:\Users\Dhanya\Anaconda3\envs\tensorflow\lib\urllib\request.py", line 248, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\Users\Dhanya\Anaconda3\envs\tensorflow\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\Dhanya\Anaconda3\envs\tensorflow\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "C:\Users\Dhanya\Anaconda3\envs\tensorflow\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\Dhanya\Anaconda3\envs\tensorflow\lib\urllib\request.py", line 570, in error
    return self._call_chain(*args)
  File "C:\Users\Dhanya\Anaconda3\envs\tensorflow\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Users\Dhanya\Anaconda3\envs\tensorflow\lib\urllib\request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

Also the url provided in the image_utils.py file is not available. 
https://github.com/PrimozGodec/ImageColorization/releases/download/v0.0.1

**Comment by PrimozGodec** [comment]
Hello, sorry for the late response. I tried today to download the model and run coloring and everything works for me. 

How did you run the script?

Path https://github.com/PrimozGodec/ImageColorization/releases/download/v0.0.1 is not available itself but python script adds the name of the file to the end and this link is available then, e.g.:
https://github.com/PrimozGodec/ImageColorization/releases/download/v0.0.1/imp9-full.h5
